//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardrobeItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WardrobeItem()
        {
            this.OutfitswiththisTop = new HashSet<Outfit>();
            this.OutfitswiththisBottom = new HashSet<Outfit>();
            this.OutfitswiththoesShoes = new HashSet<Outfit>();
            this.OutfitswiththisAccessory = new HashSet<Outfit>();
        }
    
        public int WardrobeItemID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> OutfitswiththisTop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> OutfitswiththisBottom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> OutfitswiththoesShoes { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> OutfitswiththisAccessory { get; set; }
    }
}
